#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '📝 Checking the commit message'

yarn commitlint --edit "$1"
status=$?

if [ $status -ne 0 ]; then
  echo '📃❌ Write using a Conventional Commit message to proceed!'
  exit $status
fi

echo '✅✅ Very good! Committing your changes now'
