#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '📝 Checking the commit message'

npx --no-install commitlint --edit "$1" ||
(
    echo '📃❌ Write using Conventional commit to proceed!';
    false;
)

echo '✅✅ Very good! Committing your changes now'
