#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🩺 Starting the checkout'

#yarn lint-staged

# Check ESLint Standards
yarn run lint ||
(
  echo '⚙️❌ ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
  false;
)

# Check tsconfig standards
yarn run prettier ||
(
  echo '🤡❌ Failed Type check. Make the changes required above.'
  false;
)

# If everything passes... Now we can commit
echo '✅ Every test passed!'
